[project]
name = "core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "James Leslie", email = "contactjamesleslie@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[tool.fastapi]
# Enables `uv run fastapi dev`
entrypoint = "core.server:app"

[tool.vercel]
entrypoint = "server:app"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
